### ISSUE TITLE
Include the Phoenix Framework installation as well?

### ISSUE THREAD

**Issue by jsonify** [elixir-espanol/one-shot-elixir-installation#4]
Would this benefit from adding the Phoenix Framework installation, or a prompt that asks the user if they want the installation...since the two really go hand in hand?

**Comment by Oxyrus** [comment]
That could be possible, ask the user if he wants to install Hex and Phoenix, I'll take a look later, thanks for the suggestion @jsonify

**Comment by jsonify** [comment]
Exactly. Starts making it like a Yeoman scaffolding tool, of which are
awesome.

**Comment by Oxyrus** [comment]
From now, it installs Hex by default, I'll leave it up to the user to install whatever libraries/frameworks he wants.
